# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  icl_testsweeper:
    timeout-minutes: 120
    strategy:
      matrix:
        maker: [make, cmake]
        compiler: [gnu, intel]
      fail-fast: false
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: .github/workflows/configure.sh ${{matrix.maker}} ${{matrix.compiler}}
      - name: Build
        run: .github/workflows/build.sh ${{matrix.maker}} ${{matrix.compiler}}
      - name: Test
        run: .github/workflows/test.sh ${{matrix.maker}} ${{matrix.compiler}}
